name: CI
on: [push]
jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
      - name: Run script
        run: bun index.ts
