name: CI
on: [push]
jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
      - name: Checkout
        uses: actions/checkout@v4
      - name: Run script
        run: bun test index.test.ts
      - run: yarn run dev
        timeout-minutes: 1
